Add hexo-theme-ayer
EasyHexo/Easy-Hexo pull request #227
Opened 2020-09-11 07:23 UTC by Shen-Yu

2020-09-12 08:56 UTC, Shen-Yu commented
@ChungZH 你好，我是hexo-theme-ayer的作者，如果提交的PR有所不当，请帮忙修改，谢谢

2020-09-12 09:00 UTC, ChungZH commented
问题太多了，我暂时改不过来。

请参阅 [CONTRIBUTING.md](https://github.com/EasyHexo/Easy-Hexo/blob/master/.github/CONTRIBUTING.md) 。

2020-09-12 11:37 UTC, Shen-Yu commented
@ChungZH 已经改过了~

2020-09-12 12:29 UTC, Yue-plus commented
请参照 [中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-CN.md) 修改一下排版格式。

2020-09-12 12:39 UTC, Shen-Yu commented
@Yue-plus 你好，已经改过了~

2020-09-12 13:47 UTC, Yue-plus requested changes

2020-09-12 13:47 UTC, Yue-plus commented on docs/2-Theme-use-and-config/2-19-hexo-theme-ayer/README.md
> +zh-CN（中文简体） en（English） zh-TW（中文繁体） ja（Japanese） es（Spanish） de（German） fr（French） ru（Russian） ko（Korean） vi（Vietnamese） nl（Dutch） no（Norwegian） pt（Portuguese）
多个值建议用 `；` 分开，或排成表格。

2020-09-12 13:47 UTC, Yue-plus commented on docs/2-Theme-use-and-config/2-19-hexo-theme-ayer/README.md
> +默认语言是英语，把博客目录下的 _config 文件里的 `language` 修改成以上简写即可更换语言。
建议：
```diff
-默认语言是英语，把博客目录下的 _config 文件里的 `language` 修改成以上简写即可更换语言。
+Hexo 默认语言为英语（en），请参照上表修改 Hexo 博客目录下的 `_config.yml` 文件中 `language:` 的值（第 11 行）。
```

2020-09-12 13:47 UTC, Yue-plus commented on docs/2-Theme-use-and-config/2-19-hexo-theme-ayer/README.md
> +zh-CN（中文简体） en（English） zh-TW（中文繁体） ja（Japanese） es（Spanish） de（German） fr（French） ru（Russian） ko（Korean） vi（Vietnamese） nl（Dutch） no（Norwegian） pt（Portuguese）
值建议使用符号包裹

2020-09-12 13:47 UTC, Yue-plus commented on docs/2-Theme-use-and-config/2-19-hexo-theme-ayer/README.md
> +本主题完全开源且免费，目前由我一个人维护，如果你觉得主题不错，你可以选择继续白嫖，也可以选择适当打赏我，不在于金额多少，而是能让我更有动力去维护这个主题。打赏请备注说明，谢谢~
建议：
这里的需要一些“话术”，不要给使用者一种“白嫖有罪”的感觉。
实际上 [hexo-theme-ayer 主题的开源许可证](https://github.com/Shen-Yu/hexo-theme-ayer/blob/master/LICENSE) 中明确表示了，只要给这个主题点一个 star 并且不抹掉页脚的主题仓库链接就可以 ”free“ 使用该主题。

2020-09-12 13:47 UTC, Yue-plus commented on docs/2-Theme-use-and-config/2-19-hexo-theme-ayer/README.md
> +以下是ayer主题目录下的 `_config.yml`文件配置，如果你是用方法二的npm安装，那么在根目录下的 `_config.ayer.yml` 配置就行，注意别把hexo的配置文件和主题的配置文件搞混。另外，请先确保你已经读过 [Hexo文档](https://hexo.io/zh-cn/docs/)。如果你在配置过程中有问题，请先擅用 [搜索引擎](https://cn.bing.com
英文与中文之间加空格

2020-09-12 13:47 UTC, Yue-plus commented on docs/2-Theme-use-and-config/2-19-hexo-theme-ayer/README.md
> +``` yaml
英文与中文之间加空格（检查整个配置文件）

2020-09-12 13:47 UTC, Yue-plus commented on docs/2-Theme-use-and-config/2-19-hexo-theme-ayer/README.md
> +	``` bash
这里缩进有点问题

2020-09-12 13:47 UTC, Yue-plus commented on docs/2-Theme-use-and-config/2-19-hexo-theme-ayer/README.md
> +> 插入图片的两种方法：1.引用图床，2.引用本地图片。为了防止路径出错，建议使用图床。
列表换行

2020-09-12 13:47 UTC, Yue-plus commented on docs/2-Theme-use-and-config/2-19-hexo-theme-ayer/README.md
> +### 二.可以启动但是样式变形了
这里是指 css 样式表无法加载吗？

2020-09-12 13:47 UTC, Yue-plus commented on docs/2-Theme-use-and-config/2-19-hexo-theme-ayer/README.md
> +建议每次生成站点或部署之前都用 `hexo clean` 命令清理一下缓存，另外你可能还需要刷新一下。
使用 <kbd>Ctrl</kbd> + <kbd>F5</kbd> 清除缓存并刷新页面。

2020-09-12 13:47 UTC, Yue-plus commented on docs/2-Theme-use-and-config/2-19-hexo-theme-ayer/README.md
> +站点配置文件 `_config.yml` 是hexo站点根目录下的主配置文件(还不知道是哪里的，自己google)，注意：别和 `ayer` 主题目录下的 `_config.yml` 搞混了。
这里可以直接贴出 Hexo 官网的的文档。[配置 Hexo](https://hexo.io/zh-cn/docs/configuration)
> 不要只提出问题，还要解决问题。

2020-09-12 13:47 UTC, Yue-plus commented on docs/2-Theme-use-and-config/2-19-hexo-theme-ayer/README.md
> +在 ayer 的 config 配置里的 `baidu_analytics` 填上百度统计代码中的 `hm.js` 问好后面那一串东西
[百度统计代码介绍](https://tongji.baidu.com/web/help/article?id=174&type=0)
> 大多数时候，直接贴个官方链接能节省双方很多时间

2020-09-12 13:47 UTC, Yue-plus commented on docs/2-Theme-use-and-config/2-19-hexo-theme-ayer/README.md
> +4. 首页封面和文案可以任意更换，主题内附送6张精美高清壁纸
数字左右空格

2020-09-12 13:47 UTC, Yue-plus commented on docs/2-Theme-use-and-config/2-19-hexo-theme-ayer/README.md
> +9. 支持文章字数和阅读时长统计
[不蒜子 - 极简网页计数器](http://busuanzi.ibruce.info/)

2020-09-12 13:47 UTC, Yue-plus commented on docs/2-Theme-use-and-config/2-19-hexo-theme-ayer/README.md
> +## 特性
最好在这儿说明哪些特性用到了哪些东西（贴出链接）。

2020-09-12 13:47 UTC, Yue-plus commented on docs/2-Theme-use-and-config/2-19-hexo-theme-ayer/README.md
> +在 ayer 的 config 配置里的 `baidu_analytics` 填上百度统计代码中的 `hm.js` 问好后面那一串东西
问好 → 问号

2020-09-12 13:50 UTC, Yue-plus commented
另外，需要明确【Hexo 博客目录下的 `_config.yml` 文件】与【ayer 主题目录下的 `_config.yml` 文件】。

2020-09-12 13:55 UTC, Yue-plus commented on docs/3-Plugins-use-and-config/3-8-hexo-tag-chart/README.md
> +Chartjs 是一款简单优雅的数据可视化工具，对比其他图表库如 echarts、highcharts、c3、flot、amchart等，它的画面效果、动态效果都更精致，它的 [文档首页](https://chartjs.bootcss.com/) 就透出一股小清新，基于 HTML5 Canvas，它拥有更好的性能且响应式，基本满足了一般数据展示的需要，包括折线图，条形图，饼图，散点图，雷达图，
并列项目使用顿号 `、`

2020-09-13 00:51 UTC, Shen-Yu commented
@Yue-plus 修改好了，已提交了新的 commit，如果还有问题的话，请再指出来 :smile:

2020-09-13 01:09 UTC, ChungZH commented
🎉 非常感谢您的贡献！我最后 review 后此 pr 即可合并。
作为作者，你可以在标题旁边标注你的姓名、写作时主题的版本等信息。下面是一个例子：
`# hexo-theme-amber <Badge text="@Mitscherlich"/> <Badge text="Finish"/> <Badge text="v0.1.0  rc.6"/>`
最后，我已经你拉入 EasyHexo org，请查阅邮箱。欢迎加团队 qq 群 `935778924`。

2020-09-13 05:47 UTC, merged